baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'West Texas Decision Systems'
collections_dir: collections
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

collections:
  services:
    output: true
    permalink: /:collection/:path/
  work:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
  - scope:
      type: work
    values:
      layout: work
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'pages'
    values:
      permalink: /:basename/

params:
  google_analytics_id: 'UA-165921531-1'
  global:
    header_fixed: true
  footer:
    show_menu_footer_primary: true
    show_menu_footer_secondary: true
    show_services_links: true
    show_work_links: true
  homepage:
    show_services_section: true
    services_count: 6
    show_splash_section_one: true
    splash_one_image: assets/images/undraw_post_online_dkuk.svg
    splash_one_heading: We Help Business Grow
    splash_one_paragraph:
      Lorem ipsum dolor sit amet, et essent mediocritatem quo, choro volumus
      oporteat an mei. Numquam dolores mel eu, mea docendi omittantur et, mea ea
      duis erat. Elit melius cu ius. Per ex novum tantas putant, ei his nullam
      aliquam apeirian. Aeterno quaestio constituto sea an, no eum intellegat
      assueverit.
    splash_one_link_url: work
    splash_one_link_text: Our Work
    show_partners: true
    show_work_section: true
    work_section_heading: Our Work
    work_count: 2
    show_view_all_work_button: true
  services:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/kaleidico-754543-unsplash.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Lorem ipsum dolor sit amet, et essent mediocritatem quo, choro volumus
      oporteat an mei. Numquam dolores mel eu, mea docendi omittantur et, mea ea
      duis erat. Elit melius cu ius. Per ex novum tantas putant, ei his nullam
      aliquam apeirian. Aeterno quaestio constituto sea an, no eum intellegat
      assueverit.
  contact_cta:
    heading: Ready to get started?
    subheading: Get in touch and get a quote.
    button_url: contact
    button_text: Contact us

plugins:
  - jekyll-environment-variables
